node:
  wan-rtr:
    mlag:
      address:
      backup-ip:
      members:
      peer-ip:
      sysmac:
      interfaces:
        bond01:
          clagid:
          members:
          mode:
          vlans:
    overlay:
      anycast-ip:
      vxlan:
        vni:
          vlan:
    ports:
      - swp40
      - swp41
    lacp:
      interfaces:
        members:
    switching:
      interface:
        mode:
        vlans:
    routing:
      lo: 10.44.44.44/32
      ospf:
        area:
        neighbors:
      bgp:
        asn: 65444
        underlay:
          external:
            peers:
              - swp40
              - swp41
          internal:
            peers:
      svi:
        vlansvi:
          ip:
          vlan:
          vrrp:
            mac:
            ip:
  agg-switch01:
    mlag:
      address:
      backup-ip:
      members:
      peer-ip:
      sysmac:
      interfaces:
        bond01:
          clagid:
          members:
          mode:
          vlans:
    overlay:
      anycast-ip:
      vxlan:
        vni:
          vlan:
    ports:
      - swp1
      - swp2
      - swp11
      - swp22
      - swp33
      - swp40
    lacp:
      interfaces:
        members:
    switching:
      interface:
        mode:
        vlans:
    routing:
      lo: 10.1.1.1/32
      ospf:
        area:
        neighbors:
      bgp:
        asn: 65000
        underlay:
          external:
            peers:
              - swp11
              - swp22
              - swp33
              - swp40
          internal:
            peers:
              - swp1
              - swp2
      svi:
        vlansvi:
          ip:
          vlan:
          vrrp:
            mac:
            ip:
  agg-switch02:
    mlag:
      address:
      backup-ip:
      members:
      peer-ip:
      sysmac:
      interfaces:
        bond01:
          clagid:
          members:
          mode:
          vlans:
    overlay:
      anycast-ip:
      vxlan:
        vni:
          vlan:
    ports:
      - swp1
      - swp2
      - swp11
      - swp22
      - swp33
      - swp40
    lacp:
      interfaces:
        members:
    switching:
      interface:
        mode:
        vlans:
    routing:
      lo: 10.2.2.2/32
      ospf:
        area:
        neighbors:
      bgp:
        asn: 65000
        underlay:
          external:
            peers:
              - swp11
              - swp22
              - swp33
              - swp40
          internal:
            peers:
              - swp1
              - swp2
      svi:
        vlansvi:
          ip:
          vlan:
          vrrp:
            mac:
            ip:
