---
- name: Copy FRR daemons file
  copy:
    src: daemons
    dest: /etc/frr/daemons
    backup: yes
  notify: restart frr

- name: Copy FRR configuration
  template:
    src: frr.j2
    dest: /etc/frr/frr.conf
    backup: yes
  notify: reload frr

- name: Initial Management VRF setup
  nclu:
    commit: true
    description: "Initial Management VRF setup"
    commands:
      - add interface eth0 vrf mgmt
      - add hostname "{{ inventory_hostname }}"
