---
- name: reload networking
  command: "ifreload -a"

- name: restart frr
  service:
    name: frr
    state: restarted

- name: reload frr
  service:
    name: frr
    state: reloaded

- name: restart hostapd
  service:
    name: hostapd
    state: restarted

- name: restart ntpd
  service:
    name: ntp
  state: restarted

- name: restart dhcrelay
  service:
    name: dhcrelay
  state: restarted
